apiVersion: v1
kind: ConfigMap
metadata:
  name: apowine-config
  namespace: kube-system
data:
  # Trireme General config
  apowine.log_level: debug
  apowine.log_format: human

  # Server to connect MongoDB
  apowine.server_endpoint: 10.11.242.222:27017
  apowine.server_user:
  apowine.server_password:
  apowine.server_db: drinksdb
  apowine.server_collection: drinkscollection
  apowine.server_insecure_skip_verify: "false"

  # CLient
  apowine.server_ip: http://35.194.19.126
  apowine.server_port: :3000
