apiVersion: v1
kind: ConfigMap
metadata:
  name: apowine-config
  namespace: apowine
data:
  # Trireme General config
  apowine.log_level: debug
  apowine.log_format: human

  # Server to connect MongoDB
  apowine.server_endpoint: mongodb:27017
  apowine.server_db: drinksdb
  apowine.server_collection: drinkscollection
  apowine.server_insecure_skip_verify: "false"

  # CLient
  apowine.server_ip: http:/server
  apowine.server_port: :3000
