apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: apowine-beer-getter
  namespace: apowine
  labels:
    role: client
    drink: beer
    app: beer-getter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beer-getter
  template:
    metadata:
      name: apowine-beer-getter
      labels:
        role: client
        drink: beer
        app: beer-getter
    spec:
      containers:
          - name: client
            image: aporeto/apowine-clientcurl:latest
            env:
            - name: URI
              value: "server:3000/beer/random"
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: apowine-wine-getter
  namespace: apowine
  labels:
    role: client
    drink: wine
    app: wine-getter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wine-getter
  template:
    metadata:
      name: apowine-wine-getter
      labels:
        role: client
        drink: wine
        app: wine-getter
    spec:
      containers:
          - name: client
            image: aporeto/apowine-clientcurl:latest
            env:
            - name: URI
              value: "server:3000/wine/random"
