apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  creationTimestamp: null
  labels:
    app: apowine-mongodb
  name: apowine-mongodb
  namespace: apowine
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apowine-mongodb
    spec:
      containers:
      - image: mongo:latest
        imagePullPolicy: Always
        name: apowine-mongodb
        resources: {}
status:
  replicas: 0
---
kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: apowine
spec:
  selector:
    app: apowine-mongodb
  ports:
    - protocol: TCP
      name: port2
      port: 27017
      targetPort: 27017
