apiVersion: batch/v1
kind: Job
metadata:
  name: apowine-producerwine
  labels:
      app: apowine-producerwine
      role: producer
      drink: wine
  namespace: apowine
spec:
  template:
    metadata:
      name: apowine-producerwine
      labels:
          app: apowine-producerwine
          role: producer
          drink: wine
    spec:
      containers:
      - name: apowine-producerwine
        image: aporeto/apowine-producerwine:latest
        env:
           - name: APOWINE_SERVERURI
             value: http://server.apowine.svc.cluster.local:3000/wine
      restartPolicy: OnFailure
