apiVersion: batch/v1
kind: Job
metadata:
  name: apowine-producerbeer
  labels:
      app: apowine-producerbeer
      role: producer
      drink: beer
  namespace: apowine
spec:
  template:
    metadata:
      name: apowine-producerbeer
      labels:
          app: apowine-producerbeer
          role: producer
          drink: beer
    spec:
      containers:
      - name: apowine-producerbeer
        image: aporeto/apowine-producerbeer:latest
        env:
           - name: APOWINE_SERVERURI
             value: http://server.apowine.svc.cluster.local:3000/beer
           - name: APOWINE_LOGLEVEL
             value: debug
      restartPolicy: OnFailure
