apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
      app: apowine-server
      role: backend
  name: apowine-server
  namespace: apowine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apowine-server
  template:
    metadata:
      labels:
          app: apowine-server
          role: backend
    spec:
      containers:
        - image: aporeto/apowine-server:k8s
          imagePullPolicy: Always
          env:
             - name: APOWINE_MONGOURL
               value: mongodb:27017
             - name: APOWINE_SERVERPORT
               value: :3000
             - name: APOWINE_MAKENEWCONNECTION
               value: "true"
          name: apowine-server
---
kind: Service
apiVersion: v1
metadata:
  name: server
  namespace: apowine
spec:
  selector:
      app: apowine-server
      role: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
